### ISSUE TITLE
Use curl with Openssl Engines

### ISSUE THREAD

**Issue by tbueOSB** [phytec/meta-esec-iotdm#13]
We want to use curl in combination with the TPM. Therefore we have to enable OpenSSL Engine Support in curl. Right now I am not 100% sure what we have to do here. But usually it is enough to define the compiler flag OPENSSL_LOAD_CONF. According to https://github.com/curl/curl/issues/2641 the HAVE_OPENSSL_ENGINE_H symbol needs to be defined.

**Comment by mschwan-phytec** [comment]
@tbueOSB Could you please check, if #14 fixes your issue?
